workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      xcode: 13.3
    scripts:
      - name: Install pods
        script: |
          pod install
      - name: Update pods
        script: |
          pod update
      - name: Run tests
        script: |
          bundle exec fastlane test
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
